name: Prepare Release
run-name: Preparing Release

on:
    workflow_dispatch:
    push:
        branches: master

jobs:
    checkVersion:
        name: Check that current package.json#version is not tagged
        runs-on: ubuntu
        outputs:
            version: ${{ steps.version.outputs.version }}
            commits: ${{ steps.commits.outputs.commits }}
            dobuild: ${{ steps.dobuild.outputs.dobuild }}

        steps:
            - name: "Checkout SReject/libmek.git"
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Read package.json
              id: package
              uses: gregoranders/nodejs-project-info@v0.0.21

            - name: Extract version of package.json
              id: version
              run: echo "version=${{ steps.package.outputs.version }}" >> $GITHUB_OUTPUT

            - name: Get commit messages
              id: commits
              shell: bash
              run: |
                EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
                RES=$(git log --pretty=format:'- %s' --branches=origin/v5 $(git describe --tags `git rev-list --tags --max-count=1`)..HEAD)
                echo "commits<<${EOF}" >> $GITHUB_OUTPUT
                echo "${RES}" >> $GITHUB_OUTPUT
                echo "${EOF}" >> $GITHUB_OUTPUT

            - name: 'Check: package version does not have a corrosponding git tag'
              id: dobuild
              shell: bash
              run: echo dobuild=$(git show-ref --tags --verify --quiet -- "refs/tags/v${{ steps.version.outputs.version }}" && echo 0 || echo 1) >> $GITHUB_OUTPUT

    draftRelease:
        name: Draft github release
        needs: [checkVersion]
        if: needs.checkVersion.outputs.dobuild == 1
        runs-on: ubuntu

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Compile release files
              run: npm run build

            - name: Draft Release
              uses: softprops/action-gh-release@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                token: ${{ env.GITHUB_TOKEN }}
                draft: true
                prerelease: false
                generate_release_notes: false

                tag_name: v${{ needs.checkVersion.outputs.version }}
                name: libmek v${{ needs.checkVersion.outputs.version }}
                body: ${{ needs.checkVersion.outputs.commits }}
                files: |
                    ./.dist/libmek.lua
                    ./.dist/libmek.min.lua